### ISSUE TITLE
Failed to install from Alpine linux

### ISSUE THREAD

**Issue by mrgreen3** [BiteDasher/archbashstrap#1]
Tried script from within Alpine linux and it failed. Did load all required deps from alpine repos. Even added bash to make sure it would run (Alpine uses ash by default).

It is an interesting idea, just cannot see advantage over simply using Arch media...

**Comment by BiteDasher** [comment]
Could you please show the script logs during installation?  I think looking at them I can understand what the problem is.

**Comment by BiteDasher** [comment]
(And, yes, the script was created mainly to create a chroot / systemd-nspawn-ready environment so that you can use arch whatever you want. But it can also be used to further install to disk along with the bootloader)

**Comment by mrgreen3** [comment]
I will when I get time. It takes a little while to get alpine live up and running. It might be easier to run from a systemd system (for it to work out of the box). Alpine linux is so small and light.. Will get back you ;-)

**Comment by BiteDasher** [comment]
> I will when I get time. It takes a little while to get alpine live up and running. It might be easier to run from a systemd system (for it to work out of the box). Alpine linux is so small and light.. Will get back you ;-)

@mrgreen3 Apparently you did not have the `zstd` and `xz` packages on your system, which are not supplied in alpine as dependencies for `tar`. Try installing them via `apk add` and write if it worked.

**Comment by mrgreen3** [comment]
Running again... loading everything required and choosing the correct drive ;-) script runs fine. Did notice that once I chrooted in I had no editor either nano or vi. That is not a major issue as I can edit files from alpine live. Once mounted to /mnt. Would not be difficult to add to package list. Quite impressive ;-)

**Comment by BiteDasher** [comment]
> Running again... loading everything required and choosing the correct drive ;-) script runs fine. Did notice that once I chrooted in I had no editor either nano or vi. That is not a major issue as I can edit files from alpine live. Once mounted to /mnt. Would not be difficult to add to package list. Quite impressive ;-)

You can install `vim` or `nano` after installing the system by `chroot` to a specific one and `sudo pacman -Syu vim`. At the expense of adding the editor to the list of packages. As written in the README, you can do it yourself on another machine with Arch Linux installed. To do this, take the `packages` file. Next, `pactree -l -u -s vim > 1; {cat packages; cat 1; } | sort -u> 1; mv 1 packages; rm 1`

**Comment by mrgreen3** [comment]
See that i had only one server in mirrorlist, you might want to think about pulling in pacman-mirrorlist. Wonder if this works under Void ;-)

**Comment by BiteDasher** [comment]
> See that i had only one server in mirrorlist, you might want to think about pulling in pacman-mirrorlist. Wonder if this works under Void ;-)

You can set your own mirror using the `MIRROR`= variable. Just execute `archbashstrap --help` and see all available options.
